#!/usr/bin/env bash
# set up the load balancer
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install haproxy -y
params="frontend http_web
\n\tbind *:80
\n\tstats uri /haproxy?stats
\n\tdefault_backend custom_backend
\nbackend custom_backend
\n\tbalance roundrobin
\n\tserver web-01 3.95.67.187:80 check
\n\tserver web-02 34.235.87.167:80 check"
echo -e "$params" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
